<?php
/**
 * CustomerConsentSource
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CustomerConsentSource Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerConsentSource
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'CONSENT_SOURCE_UNKNOWN';

    public const FRONTEND = 'CONSENT_SOURCE_FRONTEND';

    public const BACKOFFICE = 'CONSENT_SOURCE_BACKOFFICE';

    public const BACKEND = 'CONSENT_SOURCE_BACKEND';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::FRONTEND,
            self::BACKOFFICE,
            self::BACKEND
        ];
    }
}


