<?php
/**
 * CustomerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Customer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CDP Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Customer\Test\Api;

use \GeminiCommerce\Customer\Configuration;
use \GeminiCommerce\Customer\ApiException;
use \GeminiCommerce\Customer\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Customer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for customerAcquireSubscriber
     *
     * .
     *
     */
    public function testCustomerAcquireSubscriber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerAcquireSubscriber2
     *
     * .
     *
     */
    public function testCustomerAcquireSubscriber2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerAcquireUnsubscriber
     *
     * .
     *
     */
    public function testCustomerAcquireUnsubscriber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerAcquireUnsubscriber2
     *
     * .
     *
     */
    public function testCustomerAcquireUnsubscriber2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerAddCustomerToGroup
     *
     * .
     *
     */
    public function testCustomerAddCustomerToGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerAddCustomerToGroup2
     *
     * .
     *
     */
    public function testCustomerAddCustomerToGroup2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerAssignAgent
     *
     * .
     *
     */
    public function testCustomerAssignAgent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerBulkUpdate
     *
     * .
     *
     */
    public function testCustomerBulkUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerBulkUpdate2
     *
     * .
     *
     */
    public function testCustomerBulkUpdate2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerCreate
     *
     * .
     *
     */
    public function testCustomerCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerCreate2
     *
     * .
     *
     */
    public function testCustomerCreate2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerCreateAddress
     *
     * .
     *
     */
    public function testCustomerCreateAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerCreateAddress2
     *
     * .
     *
     */
    public function testCustomerCreateAddress2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerCreateGroup
     *
     * .
     *
     */
    public function testCustomerCreateGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerCreateGroup2
     *
     * .
     *
     */
    public function testCustomerCreateGroup2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerCreateSubscriber
     *
     * .
     *
     */
    public function testCustomerCreateSubscriber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerCreateSubscriber2
     *
     * .
     *
     */
    public function testCustomerCreateSubscriber2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerDeleteAddress
     *
     * .
     *
     */
    public function testCustomerDeleteAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerDeleteAddress2
     *
     * .
     *
     */
    public function testCustomerDeleteAddress2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerDeleteGroup
     *
     * .
     *
     */
    public function testCustomerDeleteGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerDeleteGroup2
     *
     * .
     *
     */
    public function testCustomerDeleteGroup2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFind
     *
     * .
     *
     */
    public function testCustomerFind()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFind2
     *
     * .
     *
     */
    public function testCustomerFind2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFindByEmail
     *
     * .
     *
     */
    public function testCustomerFindByEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFindByEmail2
     *
     * .
     *
     */
    public function testCustomerFindByEmail2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFindById
     *
     * .
     *
     */
    public function testCustomerFindById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFindById2
     *
     * .
     *
     */
    public function testCustomerFindById2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFindSubscriberByEmail
     *
     * .
     *
     */
    public function testCustomerFindSubscriberByEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFindSubscriberByEmail2
     *
     * .
     *
     */
    public function testCustomerFindSubscriberByEmail2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFindSubscriberById
     *
     * .
     *
     */
    public function testCustomerFindSubscriberById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerFindSubscriberById2
     *
     * .
     *
     */
    public function testCustomerFindSubscriberById2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerGetGroupByCode
     *
     * .
     *
     */
    public function testCustomerGetGroupByCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerGetGroupByCode2
     *
     * .
     *
     */
    public function testCustomerGetGroupByCode2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerGetGroupById
     *
     * .
     *
     */
    public function testCustomerGetGroupById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerGetGroupById2
     *
     * .
     *
     */
    public function testCustomerGetGroupById2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerGrantPermissions
     *
     * .
     *
     */
    public function testCustomerGrantPermissions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerGrantPermissions2
     *
     * .
     *
     */
    public function testCustomerGrantPermissions2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerListConsents
     *
     * ListConsents list all consents of a customer.
     *
     */
    public function testCustomerListConsents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerListCustomers
     *
     * .
     *
     */
    public function testCustomerListCustomers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerListCustomers2
     *
     * .
     *
     */
    public function testCustomerListCustomers2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerListGroups
     *
     * .
     *
     */
    public function testCustomerListGroups()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerListGroups2
     *
     * .
     *
     */
    public function testCustomerListGroups2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerRemoveCustomerFromGroup
     *
     * .
     *
     */
    public function testCustomerRemoveCustomerFromGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerRemoveCustomerFromGroup2
     *
     * .
     *
     */
    public function testCustomerRemoveCustomerFromGroup2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerRemoveDefaultAddress
     *
     * .
     *
     */
    public function testCustomerRemoveDefaultAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerRemoveDefaultAddress2
     *
     * .
     *
     */
    public function testCustomerRemoveDefaultAddress2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerRevokePermissions
     *
     * .
     *
     */
    public function testCustomerRevokePermissions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerRevokePermissions2
     *
     * .
     *
     */
    public function testCustomerRevokePermissions2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerSearch
     *
     * .
     *
     */
    public function testCustomerSearch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerSearch2
     *
     * .
     *
     */
    public function testCustomerSearch2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerSetDefaultAddress
     *
     * .
     *
     */
    public function testCustomerSetDefaultAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerSetDefaultAddress2
     *
     * .
     *
     */
    public function testCustomerSetDefaultAddress2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerSetPermissions
     *
     * .
     *
     */
    public function testCustomerSetPermissions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerSetPermissions2
     *
     * .
     *
     */
    public function testCustomerSetPermissions2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUnassignAgent
     *
     * .
     *
     */
    public function testCustomerUnassignAgent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUnsubscribe
     *
     * .
     *
     */
    public function testCustomerUnsubscribe()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUnsubscribe2
     *
     * .
     *
     */
    public function testCustomerUnsubscribe2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUpdate
     *
     * .
     *
     */
    public function testCustomerUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUpdate2
     *
     * .
     *
     */
    public function testCustomerUpdate2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUpdateAddress
     *
     * .
     *
     */
    public function testCustomerUpdateAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUpdateAddress2
     *
     * .
     *
     */
    public function testCustomerUpdateAddress2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUpdateGroup
     *
     * .
     *
     */
    public function testCustomerUpdateGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUpdateGroup2
     *
     * .
     *
     */
    public function testCustomerUpdateGroup2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUpdateSubscriber
     *
     * .
     *
     */
    public function testCustomerUpdateSubscriber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for customerUpdateSubscriber2
     *
     * .
     *
     */
    public function testCustomerUpdateSubscriber2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
